LTO_ENABLE		= yes
MOUSEKEY_ENABLE = yes
VIA_ENABLE		= yes
OLED_ENABLE		= yes
WPM_ENABLE		= yes

CONSOLE_ENABLE		= no
COMMAND_ENABLE		= no
SPACE_CADET_ENABLE	= no
GRAVE_ESC_ENABLE	= no
MAGIC_ENABLE		= no
MUSIC_ENABLE		= no
